import { INodeProperties } from 'n8n-workflow';

export const subscriptionOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ['subscription'],
			},
		},
		options: [
			{
				name: 'Get',
				value: 'get',
				description: 'Get subscriptions with optional filtering',
				action: 'Get subscriptions',
			},
			{
				name: 'Create',
				value: 'create',
				description: 'Create a new subscription',
				action: 'Create a subscription',
			},
			{
				name: 'Update',
				value: 'update',
				description: 'Update subscription(s)',
				action: 'Update subscriptions',
			},
		],
		default: 'create',
	},
];

export const subscriptionFields: INodeProperties[] = [
	// Get Subscriptions (GET /subscriptions with query params)
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: {
			show: {
				resource: ['subscription'],
				operation: ['get'],
			},
		},
		options: [
			{
				displayName: 'Emails',
				name: 'emails',
				type: 'string',
				default: '',
				description: 'Comma-separated emails (max 50)',
			},
			{
				displayName: 'From Date',
				name: 'fromDate',
				type: 'dateTime',
				default: '',
				description: 'Only subscriptions after this date (ISO 8601 format)',
			},
			{
				displayName: 'IDs',
				name: 'ids',
				type: 'string',
				default: '',
				description: 'Comma-separated subscription IDs (max 50)',
			},
			{
				displayName: 'Lead IDs',
				name: 'leadIds',
				type: 'string',
				default: '',
				description: 'Comma-separated lead IDs (max 50)',
			},
			{
				displayName: 'Page ID',
				name: 'pageId',
				type: 'string',
				default: '',
				description: 'Page ID for pagination (from nextPageId in response)',
			},
			{
				displayName: 'Page Size',
				name: 'pageSize',
				type: 'number',
				default: 50,
				description: 'Maximum number of subscriptions per page (1-250)',
			},
			{
				displayName: 'Product Tags',
				name: 'productTags',
				type: 'string',
				default: '',
				description: 'Comma-separated product tags (max 20)',
			},
			{
				displayName: 'Subscription States',
				name: 'subscriptionStates',
				type: 'string',
				default: '',
				description: 'Comma-separated subscription states (ACTIVE, TRIALING, CANCELED, PAST_DUE, INCOMPLETE, INCOMPLETE_EXPIRED, UNPAID, COMPLETED, PAUSED)',
			},
			{
				displayName: 'To Date',
				name: 'toDate',
				type: 'dateTime',
				default: '',
				description: 'Only subscriptions before this date (ISO 8601 format)',
			},
		],
	},
	// Create Subscription (POST /subscriptions) - Required fields
	{
		displayName: 'Status',
		name: 'status',
		type: 'options',
		required: true,
		options: [
			{ name: 'Active', value: 'ACTIVE' },
			{ name: 'Canceled', value: 'CANCELED' },
			{ name: 'Completed', value: 'COMPLETED' },
			{ name: 'Incomplete', value: 'INCOMPLETE' },
			{ name: 'Incomplete Expired', value: 'INCOMPLETE_EXPIRED' },
			{ name: 'Past Due', value: 'PAST_DUE' },
			{ name: 'Paused', value: 'PAUSED' },
			{ name: 'Trialing', value: 'TRIALING' },
			{ name: 'Unpaid', value: 'UNPAID' },
		],
		displayOptions: {
			show: {
				resource: ['subscription'],
				operation: ['create'],
			},
		},
		default: 'ACTIVE',
		description: 'Status of subscription (required)',
	},
	{
		displayName: 'Start Date',
		name: 'startDate',
		type: 'dateTime',
		required: true,
		displayOptions: {
			show: {
				resource: ['subscription'],
				operation: ['create'],
			},
		},
		default: '',
		description: 'Date on which the subscription started (ISO 8601 format, required)',
	},
	{
		displayName: 'Price',
		name: 'price',
		type: 'number',
		required: true,
		displayOptions: {
			show: {
				resource: ['subscription'],
				operation: ['create'],
			},
		},
		default: 0,
		description: 'Subscription price (required)',
	},
	{
		displayName: 'Periodicity',
		name: 'periodicity',
		type: 'options',
		required: true,
		options: [
			{ name: 'Day', value: 'DAY' },
			{ name: 'Month', value: 'MONTH' },
			{ name: 'Quarter', value: 'QUARTER' },
			{ name: 'Week', value: 'WEEK' },
			{ name: 'Year', value: 'YEAR' },
		],
		displayOptions: {
			show: {
				resource: ['subscription'],
				operation: ['create'],
			},
		},
		default: 'MONTH',
		description: 'Frequency at which subscription is billed (required)',
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['subscription'],
				operation: ['create'],
			},
		},
		options: [
			{
				displayName: 'Cancel At Date',
				name: 'cancelAtDate',
				type: 'dateTime',
				default: '',
				description: 'Date on which the subscription was canceled (ISO 8601 format)',
			},
			{
				displayName: 'Email',
				name: 'email',
				type: 'string',
				placeholder: 'name@email.com',
				default: '',
				description: 'Email associated with the lead (required if no phone number)',
			},
			{
				displayName: 'End Date',
				name: 'endDate',
				type: 'dateTime',
				default: '',
				description: 'Date on which the subscription ended (ISO 8601 format)',
			},
			{
				displayName: 'First Name',
				name: 'firstName',
				type: 'string',
				default: '',
				description: 'First name of the lead',
			},
			{
				displayName: 'Last Name',
				name: 'lastName',
				type: 'string',
				default: '',
				description: 'Last name of the lead',
			},
			{
				displayName: 'Lead IPs',
				name: 'leadIps',
				type: 'string',
				default: '',
				description: 'Comma-separated IPs of the customer (used for ad attribution)',
			},
			{
				displayName: 'Name',
				name: 'name',
				type: 'string',
				default: '',
				description: 'Name of subscription',
			},
			{
				displayName: 'Parent Email',
				name: 'parentEmail',
				type: 'string',
				default: '',
				description: 'Email of the origin lead',
			},
			{
				displayName: 'Phone Numbers',
				name: 'phoneNumbers',
				type: 'string',
				default: '',
				description: 'Comma-separated phone numbers (required if no email)',
			},
			{
				displayName: 'Plan ID',
				name: 'planId',
				type: 'string',
				default: '',
				description: 'Unique identifier of the plan from external integration',
			},
			{
				displayName: 'Stage',
				name: 'stage',
				type: 'string',
				default: '',
				description: 'The name of a stage to be applied to the customer\'s lead',
			},
			{
				displayName: 'Subscription ID',
				name: 'subscriptionId',
				type: 'string',
				default: '',
				description: 'ID of subscription',
			},
			{
				displayName: 'Trial End Date',
				name: 'trialEndDate',
				type: 'dateTime',
				default: '',
				description: 'Date on which the trial period ended (ISO 8601 format)',
			},
			{
				displayName: 'Trial Start Date',
				name: 'trialStartDate',
				type: 'dateTime',
				default: '',
				description: 'Date on which the trial period started (ISO 8601 format)',
			},
		],
	},
	// Update Subscriptions (PUT /subscriptions)
	{
		displayName: 'IDs',
		name: 'ids',
		type: 'string',
		required: true,
		displayOptions: {
			show: {
				resource: ['subscription'],
				operation: ['update'],
			},
		},
		default: '',
		description: 'Comma-separated subscription IDs to update (max 50, required)',
	},
	{
		displayName: 'Price',
		name: 'price',
		type: 'number',
		required: true,
		displayOptions: {
			show: {
				resource: ['subscription'],
				operation: ['update'],
			},
		},
		default: 0,
		description: 'Subscription price (required)',
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['subscription'],
				operation: ['update'],
			},
		},
		options: [
			{
				displayName: 'Cancel At Date',
				name: 'cancelAtDate',
				type: 'dateTime',
				default: '',
				description: 'Date on which the subscription was canceled (ISO 8601 format). Required when setting status to CANCELED.',
			},
			{
				displayName: 'End Date',
				name: 'endDate',
				type: 'dateTime',
				default: '',
				description: 'Date on which the subscription ended (ISO 8601 format)',
			},
			{
				displayName: 'Name',
				name: 'name',
				type: 'string',
				default: '',
				description: 'Name of subscription',
			},
			{
				displayName: 'Start Date',
				name: 'startDate',
				type: 'dateTime',
				default: '',
				description: 'Date on which the subscription started (ISO 8601 format)',
			},
			{
				displayName: 'Status',
				name: 'status',
				type: 'options',
				options: [
					{ name: 'Active', value: 'ACTIVE' },
					{ name: 'Canceled', value: 'CANCELED' },
					{ name: 'Completed', value: 'COMPLETED' },
					{ name: 'Incomplete', value: 'INCOMPLETE' },
					{ name: 'Incomplete Expired', value: 'INCOMPLETE_EXPIRED' },
					{ name: 'Past Due', value: 'PAST_DUE' },
					{ name: 'Paused', value: 'PAUSED' },
					{ name: 'Trialing', value: 'TRIALING' },
					{ name: 'Unpaid', value: 'UNPAID' },
				],
				default: 'ACTIVE',
				description: 'Status of subscription. NOTE: When setting to CANCELED, Cancel At Date is required by the API.',
			},
			{
				displayName: 'Trial End Date',
				name: 'trialEndDate',
				type: 'dateTime',
				default: '',
				description: 'Date on which the trial period ended (ISO 8601 format)',
			},
			{
				displayName: 'Trial Start Date',
				name: 'trialStartDate',
				type: 'dateTime',
				default: '',
				description: 'Date on which the trial period started (ISO 8601 format)',
			},
		],
	},
];
